repos:
  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.2
    hooks:
      - id: autopep8
        args: ['--max-line-length=200', '--in-place']

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: ['--max-line-length=200']

  - repo: local
    hooks:
      - id: update-version-badge
        name: Update Version Badge
        entry: python3 scripts/update_version.py
        language: python
        additional_dependencies: []
        pass_filenames: false
        files: ^(CHANGELOG\.md|README\.md)$